name: CI

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

env:
  SUBSTITUTIONS: "_PROJECT=${{ secrets.GCP_PROJECT_ID }},_REGION=us-central1,_PIPELINE_NAME=sentiment-analysis-tfx,_REPO_URL=https://github.com/leesera/ML-onboarding.git,_BRANCH=main,_BUCKET=ml-onbording/"    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: check if something changed
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: 'main'
          filters: |
            pipeline:
              - 'tfx-pipeline/**'
            modules:
              - 'modules/**'
      - name: for test 
        run: 
          gcloud builds submit --no-source --timeout=60m --config build/full-pipeline-deployment.yaml --substitutions $SUBSTITUTIONS --machine-type=n1-highcpu-8 --impersonate-service-account=729948466727-compute@developer.gserviceaccount.com
